#!/bin/bash
#PBS -P CFP03-CF-051
#PBS -j oe
#PBS -k oed
#PBS -N inference_emri
#PBS -q auto
#PBS -l select=1:ngpus=1:mem=128gb
#PBS -l walltime=8:00:00

cd $PBS_O_WORKDIR

LOG_DIR=/scratch/josh.mat/opt_grid/logs_inference
mkdir -p "$LOG_DIR"

image="/app1/common/singularity-img/hopper/cuda/cuda_12.4.1-cudnn-devel-u22.04.sif"
module load singularity

singularity exec --nv -e "$image" bash << 'EOF' > "$LOG_DIR/inference.out.$PBS_JOBID" 2> "$LOG_DIR/inference.err.$PBS_JOBID"
PYTHON=/home/svu/josh.mat/miniconda3/bin/python3
cd /home/svu/josh.mat/git_repos/bias_inference_emri/src
$PYTHON inference.py
EOF
