#!/bin/bash
#PBS -P CFP03-CF-051
#PBS -j oe
#PBS -N 1pa_overlaps
#PBS -q auto
#PBS -l select=1:ncpus=12:mpiprocs=1:ompthreads=12:mem=100gb:ngpus=1
#PBS -l walltime=04:00:00

cd $PBS_O_WORKDIR

image="/app1/common/singularity-img/hopper/cuda/cuda_12.1.0-cudnn8-devel-u20.04.sif"

module load singularity

LOG_DIR=/scratch/josh.mat/opt_grid/logs_overlaps
mkdir -p "$LOG_DIR"

singularity exec --nv -e "$image" bash << 'EOF' > "$LOG_DIR/overlaps.out.$PBS_JOBID" 2> "$LOG_DIR/overlaps.err.$PBS_JOBID"
source ~/.bashrc
conda activate few_env3
cd /scratch/josh.mat/bias_inference_emri/src
python -u compute_1pa_overlaps.py
EOF
